### ISSUE TITLE
metric-proxy pod metrics unable to fetch from prometheus in cf-for-k8s v0.6.0

### ISSUE THREAD

**Issue by PavanVasist** [cloudfoundry/metric-proxy#8]
## Describe the bug
metrics exposed from metric-proxy at port 9090 are reachable in localhost(0:9090 ---> inside the pod). But not able to reach from outside. Whereas the metrics from instio-proxy container within the pod(http://<metric-proxy-pod-IP>:15090/stats/prometheus) am able to fetch from outside(from prometheus pod).

## To Reproduce*
1. ssh into metric-proxy container within cf-system namespace and curl for 0:9090/metrics. We will be able get it.
2. Now ssh into other pod either within same namespace(cf-api-server pod) or into prometheus pod and try scraping the metrics, when doing it via prometheus pod running in different namespace we get -  
```
Get http://100.96.33.144:9090/metrics: context deadline exceeded
```
scraping via cf-api-server container within same namespace(cf-system), we get - 
```
curl: (56) Recv failure: Connection reset by peer
```

## Expected behavior
Metrics should have been scraped from 9090 port as it was able to from 15090.

### cf-for-k8s SHA 
_https://github.com/cloudfoundry/cf-for-k8s/commit/7c65597af7a4de935994813658a5db182fbecac9_

### Deploy instructions
_Deploying the release with default configurations with incluster persistence_

### Cluster information
_Using Gardener for creation of K8s cluster_

### CLI versions
_paste output of the following commands_

1. `ytt --version`: 0.30.0
2. `kapp --version`:0.33.0
3. `kubectl version`: 
```
lient Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.8", GitCommit:"35dc4cdc26cfcb6614059c4c6e836e5f0dc61dee", GitTreeState:"clean", BuildDate:"2020-06-26T03:36:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
4. `cf version`:6.52.0+b086fe522.2020-08-26

**Comment by kkburr** [comment]
@PavanVasist Can you give us more clarity on how you deployed prometheus? Were you using the instructions in [cf-for-k8s-metrics-examples](https://github.com/cloudfoundry/cf-for-k8s-metric-examples), [cf-k8s-prometheus](https://github.com/cloudfoundry/cf-k8s-prometheus) or by another means?

**Comment by PavanVasist** [comment]
Hi @kkburr - We had the below setup for prometheus.
- Deployed prometheus in another(**monitoring**) namespace using [helm chart ](https://github.com/helm/charts/tree/master/stable/prometheus)

- Created respective NetworkPolicy to allow prometheus to scrape from cf-system namespace.

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-scrape
  namespace: cf-system
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          purpose=monitoring
      podSelector:
        matchLabels:
          app=prometheus
```

- Prometheus image version - ```prom/prometheus:v2.16.0```
